# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 14:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Name_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.TextField()),
                ('name', models.TextField()),
                ('otch', models.TextField()),
                ('position', models.TextField()),
                ('job_date', models.TextField()),
                ('old_date', models.TextField()),
                ('regist', models.TextField()),
                ('adress', models.TextField()),
                ('phone', models.TextField()),
                ('email', models.TextField()),
                ('promotion', models.TextField()),
                ('rebuke', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
