# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('name_base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name_list',
            name='lastname',
            field=models.CharField(max_length=200),
        ),
    ]
