# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 16:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('name_base', '0002_auto_20171108_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name_list',
            name='adress',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='name_list',
            name='email',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='name_list',
            name='job_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='name_list',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='name_list',
            name='old_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='name_list',
            name='otch',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='name_list',
            name='phone',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='name_list',
            name='position',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='name_list',
            name='regist',
            field=models.CharField(max_length=200),
        ),
    ]
