# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('name_base', '0004_auto_20171108_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name_list',
            name='adress',
            field=models.CharField(max_length=200, verbose_name='Адрес проживания'),
        ),
        migrations.AlterField(
            model_name='name_list',
            name='email',
            field=models.CharField(max_length=200, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='name_list',
            name='job_date',
            field=models.DateTimeField(verbose_name='Дата приема'),
        ),
        migrations.AlterField(
            model_name='name_list',
            name='lastname',
            field=models.CharField(max_length=200, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='name_list',
            name='old_date',
            field=models.DateTimeField(verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='name_list',
            name='otch',
            field=models.CharField(max_length=200, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='name_list',
            name='phone',
            field=models.CharField(max_length=200, verbose_name='Контактный телефон'),
        ),
        migrations.AlterField(
            model_name='name_list',
            name='position',
            field=models.CharField(max_length=200, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='name_list',
            name='promotion',
            field=models.TextField(verbose_name='Поощрения'),
        ),
        migrations.AlterField(
            model_name='name_list',
            name='rebuke',
            field=models.TextField(verbose_name='Выговоры'),
        ),
        migrations.AlterField(
            model_name='name_list',
            name='regist',
            field=models.CharField(max_length=200, verbose_name='Место регистрации'),
        ),
    ]
