# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('name_base', '0005_auto_20171108_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='name_list',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
