# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 15:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('name_base', '0006_name_list_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='name_list',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
