# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 02:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('name_base', '0008_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='name_list',
        ),
        migrations.DeleteModel(
            name='Car',
        ),
    ]
