# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('name_base', '0009_auto_20171110_0256'),
    ]

    operations = [
        migrations.AddField(
            model_name='name_list',
            name='image',
            field=models.ImageField(blank=True, upload_to='photo/%Y/%m/%d/', verbose_name='Фотография'),
        ),
    ]
