# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('name_base', '0010_name_list_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name_list',
            name='image',
            field=models.ImageField(blank=True, upload_to='photo/', verbose_name='Фотография'),
        ),
    ]
