# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('name_base', '0014_auto_20171111_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name_list',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static', verbose_name='Фотография'),
        ),
    ]
