# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('name_base', '0018_delete_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.ImageField(upload_to='documents/%Y/%m/%d')),
            ],
        ),
    ]
