# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('name_base', '0021_article'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.RemoveField(
            model_name='name_list',
            name='author',
        ),
        migrations.RemoveField(
            model_name='name_list',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='name_list',
            name='published_date',
        ),
        migrations.AlterField(
            model_name='name_list',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='media/', verbose_name='Фотография'),
        ),
    ]
