# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 17:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('name_base', '0022_auto_20171113_1735'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='name_list',
            options={'verbose_name': 'Кадры'},
        ),
    ]
