# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('name_base', '0024_auto_20171116_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name_list',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='media/%Y/%m/%d/', verbose_name='Фотография'),
        ),
    ]
