# Generated by Django 2.2 on 2019-11-11 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('name_base', '0025_auto_20171117_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name_list',
            name='job_date',
            field=models.CharField(max_length=200, verbose_name='Дата приема'),
        ),
        migrations.AlterField(
            model_name='name_list',
            name='old_date',
            field=models.CharField(max_length=200, verbose_name='Дата рождения'),
        ),
    ]
