# Generated by Django 2.2 on 2019-11-11 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('name_base', '0026_auto_20191111_0557'),
    ]

    operations = [
        migrations.AddField(
            model_name='name_list',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
    ]
