# Generated by Django 2.2 on 2019-12-25 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('name_base', '0027_name_list_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='name_list',
            options={'verbose_name': 'Команды', 'verbose_name_plural': 'Команды'},
        ),
        migrations.RemoveField(
            model_name='name_list',
            name='adress',
        ),
        migrations.RemoveField(
            model_name='name_list',
            name='job_date',
        ),
        migrations.RemoveField(
            model_name='name_list',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='name_list',
            name='name',
        ),
        migrations.RemoveField(
            model_name='name_list',
            name='old_date',
        ),
        migrations.RemoveField(
            model_name='name_list',
            name='otch',
        ),
        migrations.RemoveField(
            model_name='name_list',
            name='position',
        ),
        migrations.RemoveField(
            model_name='name_list',
            name='regist',
        ),
        migrations.AddField(
            model_name='name_list',
            name='capitan',
            field=models.CharField(default='null', max_length=200, verbose_name='Капитан команды'),
        ),
        migrations.AddField(
            model_name='name_list',
            name='city',
            field=models.CharField(default=1, max_length=200, verbose_name='Населенный пункт'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='name_list',
            name='comandname',
            field=models.CharField(default=1, max_length=200, verbose_name='Название команды'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='name_list',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='media/%Y/%m/%d/', verbose_name='Логотип'),
        ),
    ]
