# Generated by Django 2.2 on 2019-12-25 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('name_base', '0028_auto_20191225_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name_list',
            name='capitan',
            field=models.CharField(max_length=200, verbose_name='Капитан команды'),
        ),
    ]
