# Generated by Django 2.2 on 2019-12-25 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('name_base', '0029_auto_20191225_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='name_list',
            name='mark',
            field=models.CharField(default='', max_length=200, verbose_name='Балл проекты-1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='name_list',
            name='mark10',
            field=models.CharField(default='', max_length=200, verbose_name='Балл кейсы-4'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='name_list',
            name='mark2',
            field=models.CharField(default='', max_length=200, verbose_name='Балл проекты-2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='name_list',
            name='mark3',
            field=models.CharField(default='', max_length=200, verbose_name='Балл медиа-1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='name_list',
            name='mark4',
            field=models.CharField(default='', max_length=200, verbose_name='Балл медиа-2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='name_list',
            name='mark5',
            field=models.CharField(default='', max_length=200, verbose_name='Балл медиа-3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='name_list',
            name='mark6',
            field=models.CharField(default='', max_length=200, verbose_name='Балл медиа-4'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='name_list',
            name='mark7',
            field=models.CharField(default='', max_length=200, verbose_name='Балл кейсы-1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='name_list',
            name='mark8',
            field=models.CharField(default='', max_length=200, verbose_name='Балл кейсы-2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='name_list',
            name='mark9',
            field=models.CharField(default='', max_length=200, verbose_name='Балл кейсы-3'),
            preserve_default=False,
        ),
    ]
