# Generated by Django 2.2 on 2019-12-25 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('name_base', '0030_auto_20191225_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name_list',
            name='mark',
            field=models.CharField(blank=True, max_length=200, verbose_name='Балл проекты-1'),
        ),
        migrations.AlterField(
            model_name='name_list',
            name='mark10',
            field=models.CharField(blank=True, max_length=200, verbose_name='Балл кейсы-4'),
        ),
        migrations.AlterField(
            model_name='name_list',
            name='mark2',
            field=models.CharField(blank=True, max_length=200, verbose_name='Балл проекты-2'),
        ),
        migrations.AlterField(
            model_name='name_list',
            name='mark3',
            field=models.CharField(blank=True, max_length=200, verbose_name='Балл медиа-1'),
        ),
        migrations.AlterField(
            model_name='name_list',
            name='mark4',
            field=models.CharField(blank=True, max_length=200, verbose_name='Балл медиа-2'),
        ),
        migrations.AlterField(
            model_name='name_list',
            name='mark5',
            field=models.CharField(blank=True, max_length=200, verbose_name='Балл медиа-3'),
        ),
        migrations.AlterField(
            model_name='name_list',
            name='mark6',
            field=models.CharField(blank=True, max_length=200, verbose_name='Балл медиа-4'),
        ),
        migrations.AlterField(
            model_name='name_list',
            name='mark7',
            field=models.CharField(blank=True, max_length=200, verbose_name='Балл кейсы-1'),
        ),
        migrations.AlterField(
            model_name='name_list',
            name='mark8',
            field=models.CharField(blank=True, max_length=200, verbose_name='Балл кейсы-2'),
        ),
        migrations.AlterField(
            model_name='name_list',
            name='mark9',
            field=models.CharField(blank=True, max_length=200, verbose_name='Балл кейсы-3'),
        ),
    ]
