# Generated by Django 2.2 on 2019-12-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('name_base', '0031_auto_20191225_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name_list',
            name='promotion',
            field=models.TextField(blank=True, verbose_name='Поощрения'),
        ),
        migrations.AlterField(
            model_name='name_list',
            name='rebuke',
            field=models.TextField(blank=True, verbose_name='Выговоры'),
        ),
    ]
